### ISSUE TITLE
Fatal Application Error

### ISSUE THREAD

**Issue by Raykor-DL** [ron-kemker/OpenAnnotation#17]
Hi. Your code looks great and I'd like to see it in action. I installed the prerequisite python packages and ran the build.py from Visual Studio Code and it created the annotationtool.exe file; however, when I run that exe I get an immediate fatal application error:
![image](https://user-images.githubusercontent.com/70864477/106204067-5ab31900-618a-11eb-94ed-4216faf441c1.png)

Do the prerequisites have specific versions required?

**Comment by Raykor-DL** [comment]
The application error was corrected by removing an indentation error in menu.py line 529 (had an extra space).

**Comment by Raykor-DL** [comment]
The application error was corrected by removing an indentation error in menu.py line 529 (had an extra space).

**Comment by ron-kemker** [comment]
Yeah sorry, I must have fat fingered something.  I just pushed the change.
